name: Node.js CI

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [ main ]

jobs:


  example_matrix:
    strategy:
      matrix:
        node: [12, 14, 16]
        include:
          - node: 16
            npm: 6
    runs-on: self-hosted
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - if: ${{ matrix.npm }}
        run: npm install -g npm@${{ matrix.npm }}
      - run: npm --version
